return {
	{
		ref = "physgun",
		name = "#GMOD_Physgun",
		trait = "physgun",
		amount = 1,
		tier = 2,
		alwaysUnlocked = true
	},
	{
		{
			{
				ref = "fr1",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "physgun",
				links = "parent",
				pos = VectorTable(4,4),
			},
			{
				ref = "fr2",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr1",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "fr3",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr1",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "fr4",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr2",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "fr5",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr3",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "fr6",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr4",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "fr7",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr5",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "fr8",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr6",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "fr9",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr7",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "fr10",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr8",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "fr11",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr9",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			{
				ref = "fr12",
				name = "Fire Rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr6",
				links = {"fr6","fr7"},
				pos = VectorTable(1,0),
			},
			{
				ref = "extraBatteries",
				name = "Extra Batteries",
				trait = "electrostaticBarrelBounces",
				amount = 1,
				tier = 1,
				parent = "fr12",
				links = "parent",
				pos = VectorTable(-1,-1),
			}
		},
		{
			{
				ref = "fastCaliberTechnique",
				name = "Fast Caliber Technique",
				trait = "sniperQueenFireRate",
				amount = 15,
				tier = 1,
				parent = "fr10",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "bigBombs",
				name = "Bigger Bombs",
				trait = "mortarTowerBombRadius",
				amount = 25,
				tier = 1,
				parent = "fr11",
				links = {"fr11", "fastCaliberTechnique"},
				pos = VectorTable(1,1),
			}
		},
		{
			{
				ref = "range1",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "fastCaliberTechnique",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "range3",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range1",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "range5",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range3",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "range2",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "bigBombs",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "range4",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range2",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "range6",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range4",
				links = "parent",
				pos = VectorTable(1,-1),
			}
		},
		{
			{
				ref = "biggerMines",
				name = "Bigger Mines",
				trait = "proximityMineRange",
				amount = 25,
				tier = 1,
				parent = "range5",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "betterGattlerDesign",
				name = "Better Gattler Design",
				trait = "gatlingGunKnightSpread",
				amount = -15,
				tier = 1,
				parent = "range6",
				links = "parent",
				pos = VectorTable(1,0),
			}
		},
		{
			{
				ref = "range7",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "biggerMines",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "range9",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range7",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "range11",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range9",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "range8",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "betterGattlerDesign",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "range10",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range8",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "range12",
				name = "Range",
				trait = "towerRange",
				amount = 2,
				parent = "range10",
				links = "parent",
				pos = VectorTable(-1,1),
			}
		},
		{
			{
				ref = "strongerSawblades",
				name = "Stronger Sawblades",
				trait = "sawbladeLauncherPierce",
				amount = 1,
				tier = 1,
				parent = "range11",
				links = "parent",
				pos = VectorTable(0,-1),
			},
			{
				ref = "pyroTraining",
				name = "Pyro Training",
				trait = {"fireCubeFireRate", "fireCubeRange"},
				amount = {10, 15},
				tier = 1,
				parent = "range12",
				links = "parent",
				pos = VectorTable(-1,0),
			}
		},
		{
			{
				ref = "motivation1",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "range11",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation2",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation3",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation2",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation4",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation3",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation5",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation4",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation6",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation5",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation7",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation6",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "motivation8",
				name = "Motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation7",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			{
				ref = "warHorn1",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "strongerSawblades",
				links = {"strongerSawblades", "pyroTraining"},
				pos = VectorTable(1,0),
			},
			{
				ref = "warHorn2",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn3",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn2",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn4",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn3",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn5",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn4",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn6",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn5",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn7",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn6",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "warHorn8",
				name = "War Horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn7",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			{
				ref = "mip1",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "range12",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip2",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip3",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip2",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip4",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip3",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip5",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip4",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip6",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip5",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip7",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip6",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "mip8",
				name = "Money Is Power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip7",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			{
				ref = "betterDiffraction",
				name = "Better Diffraction",
				trait = "microwaveGeneratorMicrowaveAngle",
				amount = 25,
				tier = 1,
				parent = "motivation8",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "fasterAssembly",
				name = "Faster Assembly",
				trait = "turretFactoryAbilityCooldown",
				amount = -15,
				tier = 1,
				parent = "warHorn8",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "reshapedPills",
				name = "Reshaped Pills",
				trait = {"pillLobberFlyTime", "pillLobberExploRadius", "pillLobberDirectDamage"},
				amount = {-15, 15, 1},
				tier = 1,
				parent = "mip8",
				links = "parent",
				pos = VectorTable(0,1),
			}
		},
		{
			ref = "rcmb",
			name = "RAINBOW COLOURED MASTER BEAM",
			trait = "rainbowBeamerDamage",
			amount = 100,
			tier = 2,
			parent = "betterDiffraction",
			links = {"betterDiffraction", "fasterAssembly", "reshapedPills"},
			pos = VectorTable(1,0)
		},
	},
	{
		{
			ref = "dr1",
			name = "Defence",
			trait = "targetDefence",
			amount = 2,
			parent = "physgun",
			links = "parent",
			pos = VectorTable(4,4),
			ang = 90
		},
		{
			{
				ref = "dr2",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "dr3",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr2",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "dr4",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr3",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "dr5",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr4",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "dr6",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr5",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "dr7",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = VectorTable(0,1.5),
			},
			{
				ref = "dr8",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr7",
				links = "parent",
				pos = VectorTable(0,1.5),
			},
			{
				ref = "dr9",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr8",
				links = "parent",
				pos = VectorTable(0,1.5),
			},
			{
				ref = "dr10",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr9",
				links = "parent",
				pos = VectorTable(0,1.5),
			},
			{
				ref = "dr11",
				name = "Defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr10",
				links = "parent",
				pos = VectorTable(0,1.5),
			}
		},
		{
			{
				ref = "mh1",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "oneShotProtection1",
				name = "One Shot Protection",
				trait = "targetOSP",
				amount = 1,
				tier = 1,
				parent = "dr6",
				links = "parent",
				pos = VectorTable(1.5,0),
			},
			{
				ref = "regeneration1",
				name = "Regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "oneShotProtection2",
				name = "One Shot Protection",
				trait = "targetOSP",
				amount = 1,
				tier = 1,
				parent = "dr11",
				links = "parent",
				pos = VectorTable(0,1.5),
			},
		},
		{
			{
				ref = "es1",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "oneShotProtection1",
				links = "parent",
				pos = VectorTable(1,0.5),
			},
			{
				ref = "es2",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es1",
				links = "parent",
				pos = VectorTable(1,0.5),
			},
			{
				ref = "es3",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es2",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "es4",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es3",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "es5",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es4",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "es6",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "oneShotProtection2",
				links = "parent",
				pos = VectorTable(0.5,1),
			},
			{
				ref = "es7",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es6",
				links = "parent",
				pos = VectorTable(0.5,1),
			},
			{
				ref = "es8",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es7",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "es9",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es8",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "es10",
				name = "Energy Shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es9",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			{
				ref = "mh2",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "regeneration1",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "mh3",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh2",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "mh4",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh3",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "mh5",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh4",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "mh6",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh5",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "mh7",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "regeneration1",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "mh8",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh7",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "mh9",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh8",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "mh10",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh9",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "mh11",
				name = "Maximum Health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh10",
				links = "parent",
				pos = VectorTable(0,1),
			},
		},
		{
			{
				ref = "targetArmor1",
				name = "Target Armor",
				trait = "targetArmor",
				amount = 1,
				tier = 1,
				parent = "es5",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "targetArmor2",
				name = "Target Armor",
				trait = "targetArmor",
				amount = 1,
				tier = 1,
				parent = "es10",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "regeneration2",
				name = "Regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh6",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "regeneration3",
				name = "Regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh11",
				links = "parent",
				pos = VectorTable(0,1),
			},
		},
		{
			{
				ref = "dodge1",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "targetArmor1",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "dodge2",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge1",
				links = "parent",
				pos = VectorTable(-1,0),
			},
			{
				ref = "dodge3",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge2",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "dodge4",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge3",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "dodge5",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge4",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "dodge6",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge5",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "dodge7",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "targetArmor2",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "dodge8",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge7",
				links = "parent",
				pos = VectorTable(0,-1),
			},
			{
				ref = "dodge9",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge8",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "dodge10",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge9",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "dodge11",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge10",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "dodge12",
				name = "Desperate Measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge11",
				links = "parent",
				pos = VectorTable(1,0),
			},
		},
		{
			{
				ref = "gh1",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "regeneration2",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh2",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh3",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh2",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "gh4",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh3",
				links = "parent",
				pos = VectorTable(0,1),
			},
			{
				ref = "gh5",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh4",
				links = "parent",
				pos = VectorTable(-1,1),
			},
			{
				ref = "gh6",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh5",
				links = "parent",
				pos = VectorTable(-1,0),
			},
			{
				ref = "gh7",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "regeneration3",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh8",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh7",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh9",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh8",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "gh10",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh9",
				links = "parent",
				pos = VectorTable(1,0),
			},
			{
				ref = "gh11",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh10",
				links = "parent",
				pos = VectorTable(1,-1),
			},
			{
				ref = "gh12",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh11",
				links = "parent",
				pos = VectorTable(0,-1),
			},
		},
		{
			{
				ref = "queenOfHearts",
				name = "Hail The Heart King",
				trait = "hoverballFactoryHealthAmplifier",
				amount = 20,
				tier = 1,
				parent = "gh6",
				links = {"gh6", "gh12"},
				pos = VectorTable(-1,0),
			},
			{
				ref = "gh13",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "queenOfHearts",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh14",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh13",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gh15",
				name = "Golden Health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh14",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
		{
			ref = "ydihylh",
			name = "YO DAWG I HEARD YOU LIKE HEALTH",
			trait = {"targetHealth", "targetHealthEffectiveness"},
			amount = {50, 100},
			tier = 2,
			parent = "dodge6",
			links = {"dodge6", "dodge12", "gh15"},
			pos = VectorTable(0,1),
		},
	},
	{
		{
			{
				ref = "gg1",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "physgun",
				links = "parent",
				pos = VectorTable(4,4),
				ang = 180
			},
			{
				ref = "gg2",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg1",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "incomeGrower1",
				name = "Income Grower",
				trait = "waveWaveIncome",
				amount = 2,
				tier = 1,
				parent = "gg2",
				links = "parent",
				pos = VectorTable(1,1)
			},
		},
		{
			{
				ref = "wb1",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "incomeGrower1",
				links = "parent",
				pos = VectorTable(-1,1)
			},
			{
				ref = "wb2",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb1",
				links = {"incomeGrower1", "wb1"},
				pos = VectorTable(1,0)
			},
			{
				ref = "wb3",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb1",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "wb4",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb2",
				links = {"wb2", "wb3"},
				pos = VectorTable(0,1)
			},
			{
				ref = "wb5",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb3",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "wb6",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb4",
				links = {"wb4", "wb5"},
				pos = VectorTable(0,1)
			},
			{
				ref = "wb7",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb5",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "wb8",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb6",
				links = {"wb6", "wb7"},
				pos = VectorTable(0,1)
			},
			{
				ref = "wb9",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb7",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "wb10",
				name = "Wave Bonus",
				trait = "waveIncome",
				amount = 5,
				parent = "wb8",
				links = {"wb8", "wb9"},
				pos = VectorTable(0,1)
			},
		},
		{
			ref = "incomeGrower2",
			name = "Income Grower",
			trait = "waveWaveIncome",
			amount = 2,
			tier = 1,
			parent = "wb10",
			links = {"wb9", "wb10"},
			pos = VectorTable(0,1)
		},
		{
			{
				ref = "sc1",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "incomeGrower1",
				links = {"incomeGrower1", "wb2"},
				pos = VectorTable(1,0)
			},
			{
				ref = "sc2",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc1",
				links = {"incomeGrower1", "sc1"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc3",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc1",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "sc4",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc2",
				links = {"sc2", "sc3"},
				pos = VectorTable(1,0)
			},
			{
				ref = "sc5",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc3",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "sc6",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc4",
				links = {"sc4", "sc5"},
				pos = VectorTable(1,0)
			},
			{
				ref = "sc7",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc5",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "sc8",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc6",
				links = {"sc6", "sc7"},
				pos = VectorTable(1,0)
			},
			{
				ref = "sc9",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc7",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "sc10",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc8",
				links = {"sc8", "sc9"},
				pos = VectorTable(1,0)
			},
		},
		{
			ref = "outsourcedHoverballParts",
			name = "Outsourced Hoverball Parts",
			trait = "hoverballFactoryCosts",
			amount = -10,
			tier = 1,
			parent = "sc9",
			links = {"sc9", "sc10"},
			pos = VectorTable(1,0)
		},
		{
			{
				ref = "gg3",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "incomeGrower1",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gg4",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg3",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "gg5",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg4",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "gg6",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg5",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "rainbowMassProduction",
				name = "Rainbow Mass Production",
				trait = "rainbowBeamerCosts",
				amount = -10,
				tier = 1,
				parent = "gg6",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "cheaperMines", -- prox mine cost
				name = "Cheaper Mines",
				trait = "proximityMineCosts",
				amount = -10,
				tier = 1,
				parent = "rainbowMassProduction",
				links = "parent",
				pos = VectorTable(1,1)
			},
		},
		{
			{
				ref = "sc11",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "cheaperMines",
				links = {"cheaperMines", "rainbowMassProduction"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc12",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc11",
				links = {"cheaperMines", "sc11"},
				pos = VectorTable(1,0)
			},
			{
				ref = "sc13",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc11",
				links = {"sc11", "rainbowMassProduction"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc14",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc12",
				links = {"sc12", "sc13"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc15",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc13",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc16",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc14",
				links = {"sc14", "sc15"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc17",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc15",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc18",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc16",
				links = {"sc16", "sc17"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc19",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc17",
				links = {"sc17", "outsourcedHoverballParts", "sc9"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "sc20",
				name = "Starting Cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc18",
				links = {"sc18", "sc19", "outsourcedHoverballParts"},
				pos = VectorTable(0,-1)
			},
		},
		{
			{
				ref = "tcg1",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "rainbowMassProduction",
				links = "parent",
				pos = VectorTable(-1,1)
			},
			{
				ref = "tcg2",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg1",
				links = {"rainbowMassProduction", "tcg1", "cheaperMines"},
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg3",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg1",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg4",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg2",
				links = {"tcg2", "tcg3", "cheaperMines"},
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg5",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg3",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg6",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg4",
				links = {"tcg4", "tcg5"},
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg7",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg5",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg8",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg6",
				links = {"tcg6", "tcg7"},
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg9",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg7",
				links = "parent",
				pos = VectorTable(0,1)
			},
			{
				ref = "tcg10",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg8",
				links = {"tcg8", "tcg9"},
				pos = VectorTable(0,1)
			},
		},
		{
			ref = "valuableHoverballs",
			name = "Valuable Hoverballs",
			trait = "hoverballFactoryIncome",
			amount = 5,
			tier = 1,
			parent = "tcg10",
			links = {"tcg9", "tcg10"},
			pos = VectorTable(0,1)
		},
		{
			{
				ref = "tcg11",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "valuableHoverballs",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "tcg12",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg11",
				links = {"valuableHoverballs", "tcg10", "tcg11"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "tcg13",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg11",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg14",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg12",
				links = {"tcg12", "tcg13"},
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg15",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg13",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg16",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg14",
				links = {"tcg14", "tcg15"},
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg17",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg15",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg18",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg16",
				links = {"tcg16", "tcg17"},
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg19",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg17",
				links = "parent",
				pos = VectorTable(1,0)
			},
			{
				ref = "tcg20",
				name = "Tower Cash Generation",
				trait = "towerIncome",
				amount = 0.5,
				parent = "tcg18",
				links = {"tcg18", "tcg19"},
				pos = VectorTable(1,0)
			},
		},
		{
			{
				ref = "gg7",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "cheaperMines",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "gg8",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg7",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "gg9",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg8",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "gg10",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg9",
				links = "parent",
				pos = VectorTable(1,1)
			},
			{
				ref = "freeAllyPawn",
				name = "Free Ally Pawn",
				trait = "allyPawnFirstFree",
				amount = 1,
				tier = 1,
				parent = "gg10",
				links = {"gg10", "tcg19", "tcg20"},
				pos = VectorTable(1,1)
			},
		},
		{
			{
				ref = "tc1",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "freeAllyPawn",
				links = {"freeAllyPawn", "tcg20"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc2",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc1",
				links = {"tc1", "freeAllyPawn"},
				pos = VectorTable(1,0)
			},
			{
				ref = "tc3",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc1",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc4",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc2",
				links = {"tc2", "tc3"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc5",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc3",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc6",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc4",
				links = {"tc4", "tc5"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc7",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc5",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc8",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc6",
				links = {"tc6", "tc7"},
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc9",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc7",
				links = "parent",
				pos = VectorTable(0,-1)
			},
			{
				ref = "tc10",
				name = "Tower Costs",
				trait = "towerCosts",
				amount = -1,
				parent = "tc8",
				links = {"tc8", "tc9"},
				pos = VectorTable(0,-1)
			},
		},
		{
			ref = "modularMicrowaveEmitters",
			name = "Modular Microwave Emitters",
			trait = "microwaveGeneratorCosts",
			amount = -10,
			tier = 1,
			parent = "tc9",
			links = {"tc9", "tc10"},
			pos = VectorTable(0,-1)
		},
		{
			{
				ref = "gg11",
				name = "Gold Glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "freeAllyPawn",
				links = "parent",
				pos = VectorTable(1,1),
			},
			{
				ref = "atgig",
				name = "ALL THAT GLITTERS IS GOLD",
				trait = "gBlimpOuterHealthCash",
				amount = 100,
				tier = 2,
				parent = "gg11",
				links = "parent",
				pos = VectorTable(1,1),
			},
		},
	},
	{
		{
			{
				ref = "mgb1",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(4,4),
				parent = "physgun",
				ang = 270
			},
			{
				ref = "mgb2",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "mgb1",
			},
			{
				ref = "mgb3",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "mgb2",
			},
			{
				ref = "mgb4",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(-1,1),
				parent = "mgb3",
			},
			{
				ref = "mgb5",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(-1,1),
				parent = "mgb4",
			},
			{
				ref = "mgb6",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "mgb5",
			},
			{
				ref = "mgb7",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,-1),
				parent = "mgb3",
			},
			{
				ref = "mgb8",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,-1),
				parent = "mgb7",
			},
			{
				ref = "mgb9",
				name = "Misconfigured gBalloons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "mgb8",
			},
		},
		{
			{
				ref = "cloglessGlueNozzle",
				name = "Clogless Glue Nozzle",
				trait = "bishopOfGlueFireRate",
				amount = 15,
				tier = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "mgb6"
			},
			{
				ref = "excessFreezing",
				name = "Excess Freezing",
				trait = "orbOfColdSpeedPercent",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "mgb9"
			},
			{
				ref = "gbs1",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = {"cloglessGlueNozzle", "excessFreezing"},
				pos = VectorTable(1,-1),
				parent = "cloglessGlueNozzle"
			}
		},
		{
			{
				ref = "gbs2",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "cloglessGlueNozzle"
			},
			{
				ref = "gbs3",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbs2"
			},
			{
				ref = "gbs4",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbs3"
			},
			{
				ref = "gbs5",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbs4"
			},
			{
				ref = "gbs6",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbs5"
			},
			{
				ref = "gbs7",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0.5,1),
				parent = "gbs6"
			},
			{
				ref = "gbs8",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0.5,1),
				parent = "gbs7"
			},
		},
		{
			{
				ref = "gbs9",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "excessFreezing"
			},
			{
				ref = "gbs10",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbs9"
			},
			{
				ref = "gbs11",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbs10"
			},
			{
				ref = "gbs12",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbs11"
			},
			{
				ref = "gbs13",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbs12"
			},
			{
				ref = "gbs14",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0.5),
				parent = "gbs13"
			},
			{
				ref = "gbs15",
				name = "gBalloon Sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0.5),
				parent = "gbs14"
			},
		},
		{
			{
				ref = "notSoFast",
				name = "Not So Fast",
				trait = "gBalloonFastSpeed",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "gbs8"
			},
			{
				ref = "notSoHealthy",
				name = "Not So Healthy",
				trait = "gBalloonRegenRate",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "gbs15"
			}
		},
		{
			{
				ref = "agbs1",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,-1),
				parent = "notSoFast"
			},
			{
				ref = "agbs2",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,-1),
				parent = "agbs1"
			},
			{
				ref = "agbs3",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,-1),
				parent = "agbs2"
			},
			{
				ref = "agbs4",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(-1,1),
				parent = "notSoHealthy"
			},
			{
				ref = "agbs5",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(-1,1),
				parent = "agbs4"
			},
			{
				ref = "agbs6",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(-1,1),
				parent = "agbs5"
			},
			{
				ref = "causalityExplosions",
				name = "Causality Explosions",
				trait = "gBalloonErrorExplosionUnimmune",
				amount = 1,
				tier = 1,
				links = {"agbs3", "agbs6"},
				pos = VectorTable(1,-1),
				parent = "agbs3"
			},
		},
		{
			{
				ref = "agbs7",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "causalityExplosions"
			},
			{
				ref = "agbs8",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "agbs7"
			},
			{
				ref = "bigArmorMalfunction",
				name = "Big Armor Malfunction",
				trait = "gBlimpArmoredArmor",
				amount = -2,
				tier = 1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "agbs8"
			},
			{
				ref = "agbs9",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(-1,-1),
				parent = "causalityExplosions"
			},
			{
				ref = "agbs10",
				name = "Advanced gBlimp Sabotage",
				trait = "gBlimpOuterHealth",
				amount = -1,
				links = "parent",
				pos = VectorTable(-1,-1),
				parent = "agbs9"
			},
			{
				ref = "fimtrtm",
				name = "Fire Is More Technological Rather Than Magical",
				trait = "gBalloonFireGeneric",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = VectorTable(-1,-1),
				parent = "agbs10"
			},
		},
		{
			{
				ref = "fab1",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "causalityExplosions"
			},
			{
				ref = "fab2",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "fab1"
			},
			{
				ref = "fab3",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "fab2"
			},
			{
				ref = "wip1",
				name = "WIP",
				trait = "",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "fab3"
			}
		},
		{
			{
				ref = "fab4",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "causalityExplosions"
			},
			{
				ref = "fab5",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "fab4"
			},
			{
				ref = "fab6",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "fab5"
			},
			{
				ref = "wip2",
				name = "WIP",
				trait = "",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "fab6"
			}
		},
		{
			{
				ref = "fab7",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,-1),
				parent = "causalityExplosions"
			},
			{
				ref = "fab8",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,-1),
				parent = "fab7"
			},
			{
				ref = "fab9",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(0,-1),
				parent = "fab8"
			},
			{
				ref = "wip3",
				name = "WIP",
				trait = "",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = VectorTable(0,-1),
				parent = "fab9"
			}
		},
		{
			{
				ref = "fab10",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(-1,0),
				parent = "causalityExplosions"
			},
			{
				ref = "fab11",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(-1,0),
				parent = "fab10"
			},
			{
				ref = "fab12",
				name = "Fair And Balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(-1,0),
				parent = "fab11"
			},
			{
				ref = "wip4",
				name = "WIP",
				trait = "",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = VectorTable(-1,0),
				parent = "fab12"
			}
		},
		{
			{
				ref = "gbls1",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "notSoFast"
			},
			{
				ref = "gbls2",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "gbls1"
			},
			{
				ref = "gbls3",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0.5),
				parent = "gbls2"
			},
			{
				ref = "gbls4",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0.5),
				parent = "gbls3"
			},
			{
				ref = "gbls5",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbls4"
			},
			{
				ref = "gbls6",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,0),
				parent = "gbls5"
			},
			{
				ref = "gbls7",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,-0.5),
				parent = "gbls6"
			},
			{
				ref = "gbls8",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,-0.5),
				parent = "gbls7"
			},
		},
		{
			{
				ref = "gbls9",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "notSoHealthy"
			},
			{
				ref = "gbls10",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(1,1),
				parent = "gbls9"
			},
			{
				ref = "gbls11",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0.5,1),
				parent = "gbls10"
			},
			{
				ref = "gbls12",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0.5,1),
				parent = "gbls11"
			},
			{
				ref = "gbls13",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbls12"
			},
			{
				ref = "gbls14",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(0,1),
				parent = "gbls13"
			},
			{
				ref = "gbls15",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(-0.5,1),
				parent = "gbls14"
			},
			{
				ref = "gbls16",
				name = "gBlimp Sabotage",
				trait = "gBlimpSpeed",
				amount = -1,
				links = "parent",
				pos = VectorTable(-0.5,1),
				parent = "gbls15"
			},
		},
		{
			ref = "hdtgpqa",
			name = "HOW DID THIS GET PAST QUALITY ASSURANCE",
			trait = "gBalloonOuterArmor",
			amount = -1,
			tier = 2,
			links = {"gbls8", "gbls16"},
			pos = VectorTable(1,-1),
			parent = "gbls8"
		},
	}
}