return {
	{
		ref = "physgun",
		name = "physgun",
		trait = "physgun",
		amount = 1,
		tier = 2,
		alwaysUnlocked = true
	},
	{
		{
			{
				ref = "fr1",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "physgun",
				links = "parent",
				pos = {4,4},
			},
			{
				ref = "fr2",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr1",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "fr3",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr1",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "fr4",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr2",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "fr5",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr3",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "fr6",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr4",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "fr7",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr5",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "fr8",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr6",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "fr9",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr7",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "fr10",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr8",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "fr11",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr9",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "fr12",
				name = "fire_rate",
				trait = "towerFireRate",
				amount = 1,
				parent = "fr6",
				links = {"fr6","fr7"},
				pos = {1,0},
			},
			{
				ref = "extraBatteries",
				name = "extra_batteries",
				trait = "electrostaticBarrelBounces",
				amount = 1,
				tier = 1,
				parent = "fr12",
				links = "parent",
				pos = {-1,-1},
			}
		},
		{
			{
				ref = "fastCaliberTechnique",
				name = "fast_caliber_technique",
				trait = "sniperQueenFireRate",
				amount = 15,
				tier = 1,
				parent = "fr10",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "bigBombs",
				name = "bigger_bombs",
				trait = "mortarTowerBombRadius",
				amount = 25,
				tier = 1,
				parent = "fr11",
				links = {"fr11", "fastCaliberTechnique"},
				pos = {1,1},
			}
		},
		{
			{
				ref = "range1",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "fastCaliberTechnique",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "range3",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range1",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "range5",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range3",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "range2",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "bigBombs",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "range4",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range2",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "range6",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range4",
				links = "parent",
				pos = {1,-1},
			}
		},
		{
			{
				ref = "biggerMines",
				name = "bigger_mines",
				trait = "proximityMineRange",
				amount = 25,
				tier = 1,
				parent = "range5",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "betterGattlerDesign",
				name = "better_gattler_design",
				trait = "gatlingGunKnightSpread",
				amount = -15,
				tier = 1,
				parent = "range6",
				links = "parent",
				pos = {1,0},
			}
		},
		{
			{
				ref = "range7",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "biggerMines",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "range9",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range7",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "range11",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range9",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "range8",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "betterGattlerDesign",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "range10",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range8",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "range12",
				name = "range",
				trait = "towerRange",
				amount = 2,
				parent = "range10",
				links = "parent",
				pos = {-1,1},
			}
		},
		{
			{
				ref = "strongerSawblades",
				name = "stronger_sawblades",
				trait = "sawbladeLauncherPierce",
				amount = 1,
				tier = 1,
				parent = "range11",
				links = "parent",
				pos = {0,-1},
			},
			{
				ref = "pyroTraining",
				name = "pyro_training",
				trait = {"fireCubeFireRate", "fireCubeRange"},
				amount = {10, 15},
				tier = 1,
				parent = "range12",
				links = "parent",
				pos = {-1,0},
			}
		},
		{
			{
				ref = "motivation1",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "range11",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation2",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation3",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation2",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation4",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation3",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation5",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation4",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation6",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation5",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation7",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation6",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "motivation8",
				name = "motivation",
				trait = "towerEarlyFireRate",
				amount = 3,
				parent = "motivation7",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "warHorn1",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "strongerSawblades",
				links = {"strongerSawblades", "pyroTraining"},
				pos = {1,0},
			},
			{
				ref = "warHorn2",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn3",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn2",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn4",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn3",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn5",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn4",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn6",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn5",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn7",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn6",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "warHorn8",
				name = "war_horn",
				trait = "towerAbilityD3FireRate",
				amount = 5,
				parent = "warHorn7",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "mip1",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "range12",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip2",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip3",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip2",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip4",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip3",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip5",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip4",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip6",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip5",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip7",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip6",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "mip8",
				name = "money_is_power",
				trait = "towerMoneyFireRate",
				amount = 0.15,
				parent = "mip7",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "betterDiffraction",
				name = "better_diffraction",
				trait = "microwaveGeneratorMicrowaveAngle",
				amount = 25,
				tier = 1,
				parent = "motivation8",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "fasterAssembly",
				name = "faster_assembly",
				trait = "turretFactoryAbilityCooldown",
				amount = -15,
				tier = 1,
				parent = "warHorn8",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "reshapedPills",
				name = "reshaped_pills",
				trait = {"pillLobberFlyTime", "pillLobberExploRadius", "pillLobberDirectDamage"},
				amount = {-15, 15, 1},
				tier = 1,
				parent = "mip8",
				links = "parent",
				pos = {0,1},
			}
		},
		{
			ref = "rcmb",
			name = "rainbow_coloured_master_beam",
			trait = "rainbowBeamerDamage",
			amount = 100,
			tier = 2,
			parent = "betterDiffraction",
			links = {"betterDiffraction", "fasterAssembly", "reshapedPills"},
			pos = {1,0}
		},
	},
	{
		{
			ref = "dr1",
			name = "defence",
			trait = "targetDefence",
			amount = 2,
			parent = "physgun",
			links = "parent",
			pos = {4,4},
			ang = 90
		},
		{
			{
				ref = "dr2",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "dr3",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr2",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "dr4",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr3",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "dr5",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr4",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "dr6",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr5",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "dr7",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = {0,1.5},
			},
			{
				ref = "dr8",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr7",
				links = "parent",
				pos = {0,1.5},
			},
			{
				ref = "dr9",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr8",
				links = "parent",
				pos = {0,1.5},
			},
			{
				ref = "dr10",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr9",
				links = "parent",
				pos = {0,1.5},
			},
			{
				ref = "dr11",
				name = "defence",
				trait = "targetDefence",
				amount = 2,
				parent = "dr10",
				links = "parent",
				pos = {0,1.5},
			}
		},
		{
			{
				ref = "mh1",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "dr1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "oneShotProtection1",
				name = "one_shot_protection",
				trait = "targetOSP",
				amount = 1,
				tier = 1,
				parent = "dr6",
				links = "parent",
				pos = {1.5,0},
			},
			{
				ref = "regeneration1",
				name = "regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "oneShotProtection2",
				name = "one_shot_protection",
				trait = "targetOSP",
				amount = 1,
				tier = 1,
				parent = "dr11",
				links = "parent",
				pos = {0,1.5},
			},
		},
		{
			{
				ref = "es1",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "oneShotProtection1",
				links = "parent",
				pos = {1,0.5},
			},
			{
				ref = "es2",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es1",
				links = "parent",
				pos = {1,0.5},
			},
			{
				ref = "es3",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es2",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "es4",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es3",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "es5",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es4",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "es6",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "oneShotProtection2",
				links = "parent",
				pos = {0.5,1},
			},
			{
				ref = "es7",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es6",
				links = "parent",
				pos = {0.5,1},
			},
			{
				ref = "es8",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es7",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "es9",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es8",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "es10",
				name = "energy_shield",
				trait = "targetShield",
				amount = 0.5,
				parent = "es9",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "mh2",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "regeneration1",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "mh3",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh2",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "mh4",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh3",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "mh5",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh4",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "mh6",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh5",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "mh7",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "regeneration1",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "mh8",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh7",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "mh9",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh8",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "mh10",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh9",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "mh11",
				name = "maximum_health",
				trait = "targetHealth",
				amount = 2,
				parent = "mh10",
				links = "parent",
				pos = {0,1},
			},
		},
		{
			{
				ref = "targetArmor1",
				name = "armor",
				trait = "targetArmor",
				amount = 1,
				tier = 1,
				parent = "es5",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "targetArmor2",
				name = "armor",
				trait = "targetArmor",
				amount = 1,
				tier = 1,
				parent = "es10",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "regeneration2",
				name = "regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh6",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "regeneration3",
				name = "regeneration",
				trait = "targetRegeneration",
				amount = 1,
				tier = 1,
				parent = "mh11",
				links = "parent",
				pos = {0,1},
			},
		},
		{
			{
				ref = "dodge1",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "targetArmor1",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "dodge2",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge1",
				links = "parent",
				pos = {-1,0},
			},
			{
				ref = "dodge3",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge2",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "dodge4",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge3",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "dodge5",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge4",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "dodge6",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge5",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "dodge7",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "targetArmor2",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "dodge8",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge7",
				links = "parent",
				pos = {0,-1},
			},
			{
				ref = "dodge9",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge8",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "dodge10",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge9",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "dodge11",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge10",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "dodge12",
				name = "desperate_measures",
				trait = "targetDodge",
				amount = 1,
				parent = "dodge11",
				links = "parent",
				pos = {1,0},
			},
		},
		{
			{
				ref = "gh1",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "regeneration2",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh2",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh3",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh2",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "gh4",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh3",
				links = "parent",
				pos = {0,1},
			},
			{
				ref = "gh5",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh4",
				links = "parent",
				pos = {-1,1},
			},
			{
				ref = "gh6",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh5",
				links = "parent",
				pos = {-1,0},
			},
			{
				ref = "gh7",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "regeneration3",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh8",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh7",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh9",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh8",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "gh10",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh9",
				links = "parent",
				pos = {1,0},
			},
			{
				ref = "gh11",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh10",
				links = "parent",
				pos = {1,-1},
			},
			{
				ref = "gh12",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh11",
				links = "parent",
				pos = {0,-1},
			},
		},
		{
			{
				ref = "queenOfHearts",
				name = "hail_the_heart_king",
				trait = "hoverballFactoryHealthAmplifier",
				amount = 20,
				tier = 1,
				parent = "gh6",
				links = {"gh6", "gh12"},
				pos = {-1,0},
			},
			{
				ref = "gh13",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "queenOfHearts",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh14",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh13",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gh15",
				name = "golden_health",
				trait = "targetGoldenHealth",
				amount = 2,
				parent = "gh14",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			ref = "ydihylh",
			name = "ydihylh",
			trait = {"targetHealth", "targetHealthEffectiveness"},
			amount = {50, 100},
			tier = 2,
			parent = "dodge6",
			links = {"dodge6", "dodge12", "gh15"},
			pos = {0,1},
		},
		{
			ref = "mh12",
			name = "maximum_health",
			trait = "targetHealth",
			amount = 2,
			parent = "ydihylh",
			links = "parent",
			pos = {1,1},
		},
		{
			ref = "mh13",
			name = "maximum_health",
			trait = "targetHealth",
			amount = 2,
			parent = "mh12",
			links = "parent",
			pos = {1,1},
		},
	},
	{
		{
			{
				ref = "gg1",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "physgun",
				links = "parent",
				pos = {4,4},
				ang = 180
			},
			{
				ref = "gg2",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg1",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "gg3",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg2",
				links = "parent",
				pos = {1,1}
			},
			{
				ref = "gg4",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg1",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "gg5",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg4",
				links = "parent",
				pos = {1,1}
			},
		},
		{
			{
				ref = "wb1",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "gg3",
				links = "parent",
				pos = {1,1}
			},
			{
				ref = "wb2",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb1",
				links = "parent",
				pos = {-1,0}
			},
			{
				ref = "wb3",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb1",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "wb4",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb2",
				links = {"wb2", "wb3"},
				pos = {0,1}
			},
			{
				ref = "wb5",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb3",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "wb6",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb4",
				links = {"wb4", "wb5"},
				pos = {0,1}
			},
			{
				ref = "wb7",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb5",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "wb8",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb6",
				links = {"wb6", "wb7"},
				pos = {0,1}
			},
			{
				ref = "wb9",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb7",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "wb10",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb8",
				links = {"wb8", "wb9"},
				pos = {0,1}
			},
		},
		{
			{
				ref = "startupAid1",
				name = "startup_aid",
				trait = "earlyWaveIncome",
				amount = 40,
				tier = 1,
				parent = "wb9",
				links = {"wb9", "wb10"},
				pos = {0,1}
			},
			{
				ref = "wb11",
				name = "wave_bonus",
				trait = "waveIncome",
				amount = 2,
				parent = "wb9",
				links = {"wb7", "wb9", "startupAid1"},
				pos = {1,0}
			},
			{
				ref = "startupAid2",
				name = "startup_aid",
				trait = "earlyWaveIncome",
				amount = 40,
				tier = 1,
				parent = "wb1",
				links = {"wb1", "wb2"},
				pos = {0,-1}
			},
			{
				ref = "gg26",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "wb1",
				links = {"wb1", "wb3"},
				pos = {1,0}
			},
		},
		{
			{
				ref = "sc1",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "gg5",
				links = {"gg5", "startupAid2", "gg26"},
				pos = {1,1}
			},
			{
				ref = "sc2",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc1",
				links = {"sc1", "startupAid2"},
				pos = {0,-1}
			},
			{
				ref = "sc3",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc1",
				links = {"sc1", "gg26"},
				pos = {1,0}
			},
			{
				ref = "sc4",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc2",
				links = {"sc2", "sc3"},
				pos = {1,0}
			},
			{
				ref = "sc5",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc3",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "sc6",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc4",
				links = {"sc4", "sc5"},
				pos = {1,0}
			},
			{
				ref = "sc7",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc5",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "sc8",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc6",
				links = {"sc6", "sc7"},
				pos = {1,0}
			},
			{
				ref = "sc9",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc7",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "sc10",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc8",
				links = {"sc8", "sc9"},
				pos = {1,0}
			},
		},
		{
			{
				ref = "efficientFactorization",
				name = "efficient_factorization",
				trait = "hoverballFactoryTowerCost",
				amount = -10,
				tier = 1,
				parent = "sc9",
				links = {"sc9", "sc10"},
				pos = {1,0}
			},
			{
				ref = "sc21",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc9",
				links = {"sc7", "sc9"},
				pos = {0,1}
			},
		},
		{
			{
				ref = "gg6",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "wb1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg7",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg6",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg8",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg7",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg9",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg8",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg10",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "sc1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg11",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg10",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg12",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg11",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg13",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg12",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "sc11",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "efficientFactorization",
				links = {"efficientFactorization", "sc21"},
				pos = {0,1}
			},
			{
				ref = "sc12",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc11",
				links = {"efficientFactorization", "sc11"},
				pos = {1,0}
			},
			{
				ref = "sc13",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc11",
				links = {"sc11", "sc21"},
				pos = {0,1}
			},
			{
				ref = "sc14",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc12",
				links = {"sc12", "sc13"},
				pos = {0,1}
			},
			{
				ref = "sc15",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc13",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "sc16",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc14",
				links = {"sc14", "sc15"},
				pos = {0,1}
			},
			{
				ref = "sc17",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc15",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "sc18",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc16",
				links = {"sc16", "sc17"},
				pos = {0,1}
			},
			{
				ref = "sc19",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc17",
				links = {"sc17", "gg13"},
				pos = {0,1}
			},
			{
				ref = "sc20",
				name = "starting_cash",
				trait = "startingCash",
				amount = 25,
				parent = "sc18",
				links = {"sc18", "sc19"},
				pos = {0,1}
			},
		},
		{
			{
				ref = "rainbowMassProduction",
				name = "rainbow_factorization",
				trait = "rainbowBeamerCosts",
				amount = -10,
				tier = 1,
				parent = "sc19",
				links = {"sc17", "sc19"},
				pos = {-1,0}
			},
			{
				ref = "cheaperMines",
				name = "cheaper_mines",
				trait = "proximityMineCosts",
				amount = -10,
				tier = 1,
				parent = "sc19",
				links = {"sc19", "sc20"},
				pos = {0,1}
			},
		},
		{
			{
				ref = "ed1",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "gg9",
				links = {"gg9", "rainbowMassProduction", "cheaperMines"},
				pos = {1,1}
			},
			{
				ref = "ed2",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed1",
				links = {"rainbowMassProduction", "ed1"},
				pos = {-1,0}
			},
			{
				ref = "ed3",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed1",
				links = {"ed1", "cheaperMines"},
				pos = {0,1}
			},
			{
				ref = "ed4",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed2",
				links = {"ed2", "ed3"},
				pos = {0,1}
			},
			{
				ref = "ed5",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed3",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "ed6",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed4",
				links = {"ed4", "ed5"},
				pos = {0,1}
			},
			{
				ref = "ed7",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed5",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "ed8",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed6",
				links = {"ed6", "ed7"},
				pos = {0,1}
			},
			{
				ref = "ed9",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed7",
				links = "parent",
				pos = {0,1}
			},
			{
				ref = "ed10",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed8",
				links = {"ed8", "ed9"},
				pos = {0,1}
			},
		},
		{
			{
				ref = "outsourcedHoverballParts",
				name = "outsourced_hoverball_parts",
				trait = "hoverballFactoryUpgradeCostsFlat",
				amount = -100,
				tier = 1,
				parent = "ed9",
				links = {"ed9", "ed10"},
				pos = {0,1}
			},
			{
				ref = "ed21",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed9",
				links = {"ed7", "ed9"},
				pos = {1,0}
			},
		},
		{
			{
				ref = "gg14",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "ed1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg15",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg14",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg16",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg15",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg17",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg16",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg18",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "sc19",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg19",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg18",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg20",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg19",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg21",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg20",
				links = "parent",
				pos = {1,1},
			},
		},
		{
			{
				ref = "ed11",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "outsourcedHoverballParts",
				links = {"outsourcedHoverballParts", "ed21"},
				pos = {1,0}
			},
			{
				ref = "ed12",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed11",
				links = {"outsourcedHoverballParts", "ed11"},
				pos = {0,1}
			},
			{
				ref = "ed13",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed11",
				links = {"ed11", "ed21"},
				pos = {1,0}
			},
			{
				ref = "ed14",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed12",
				links = {"ed12", "ed13"},
				pos = {1,0}
			},
			{
				ref = "ed15",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed13",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "ed16",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed14",
				links = {"ed14", "ed15"},
				pos = {1,0}
			},
			{
				ref = "ed17",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed15",
				links = "parent",
				pos = {1,0}
			},
			{
				ref = "ed18",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed16",
				links = {"ed16", "ed17"},
				pos = {1,0}
			},
			{
				ref = "ed19",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed17",
				links = {"ed17", "gg17"},
				pos = {1,0}
			},
			{
				ref = "ed20",
				name = "easy_deployment",
				trait = "towerPlaceCost",
				amount = -1,
				parent = "ed18",
				links = {"ed18", "ed19"},
				pos = {1,0}
			},
		},
		{
			{
				ref = "freeAllyPawn",
				name = "free_ally_pawn",
				trait = "allyPawnFirstFree",
				amount = 1,
				tier = 1,
				parent = "ed19",
				links = {"ed19", "ed20"},
				pos = {1,0}
			},
			{
				ref = "gg27",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "ed19",
				links = {"ed17", "ed19"},
				pos = {0,-1},
			},
		},
		{
			{
				ref = "tcg1",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "gg21",
				links = {"gg21", "freeAllyPawn", "gg27"},
				pos = {1,1}
			},
			{
				ref = "tcg2",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg1",
				links = {"tcg1", "freeAllyPawn"},
				pos = {1,0}
			},
			{
				ref = "tcg3",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg1",
				links = {"tcg1", "gg27"},
				pos = {0,-1}
			},
			{
				ref = "tcg4",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg2",
				links = {"tcg2", "tcg3"},
				pos = {0,-1}
			},
			{
				ref = "tcg5",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg3",
				links = "parent",
				pos = {0,-1}
			},
			{
				ref = "tcg6",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg4",
				links = {"tcg4", "tcg5"},
				pos = {0,-1}
			},
			{
				ref = "tcg7",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg5",
				links = "parent",
				pos = {0,-1}
			},
			{
				ref = "tcg8",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg6",
				links = {"tcg6", "tcg7"},
				pos = {0,-1}
			},
			{
				ref = "tcg9",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg7",
				links = "parent",
				pos = {0,-1}
			},
			{
				ref = "tcg10",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg8",
				links = {"tcg8", "tcg9"},
				pos = {0,-1}
			},
			{
				ref = "modularMicrowaveEmitters",
				name = "modular_microwave_emitters",
				trait = "microwaveGeneratorCosts",
				amount = -10,
				tier = 1,
				parent = "tcg9",
				links = {"tcg9", "tcg10"},
				pos = {0,-1}
			},
			{
				ref = "tcg11",
				name = "tower_cash_generation",
				trait = "towerIncome",
				amount = 1,
				parent = "tcg9",
				links = {"tcg7", "tcg9", "modularMicrowaveEmitters"},
				pos = {-1,0}
			},
		},
		{
			{
				ref = "gg22",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "ed19",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg23",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg22",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg24",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "tcg1",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "gg25",
				name = "gold_glitters",
				trait = "cashFromBalloons",
				amount = 1,
				parent = "gg24",
				links = "parent",
				pos = {1,1},
			},
			{
				ref = "atgig",
				name = "all_that_glitters_is_gold",
				trait = "gBlimpAndBossOuterHealthCash",
				amount = 200,
				tier = 2,
				parent = "gg23",
				links = {"gg23", "gg25"},
				pos = {1,0},
			},
		},
	},
	{
		{
			{
				ref = "mgb1",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {4,4},
				parent = "physgun",
				ang = 270
			},
			{
				ref = "mgb2",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {1,1},
				parent = "mgb1",
			},
			{
				ref = "mgb3",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {1,1},
				parent = "mgb2",
			},
			{
				ref = "mgb4",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {-1,1},
				parent = "mgb3",
			},
			{
				ref = "mgb5",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {-1,1},
				parent = "mgb4",
			},
			{
				ref = "mgb6",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {1,0},
				parent = "mgb5",
			},
			{
				ref = "mgb7",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {1,-1},
				parent = "mgb3",
			},
			{
				ref = "mgb8",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {1,-1},
				parent = "mgb7",
			},
			{
				ref = "mgb9",
				name = "misconfigured_gballoons",
				trait = "gBalloonMissingProperty",
				amount = 1,
				links = "parent",
				pos = {0,1},
				parent = "mgb8",
			},
		},
		{
			{
				ref = "cloglessGlueNozzle",
				name = "clogless_glue_nozzle",
				trait = "bishopOfGlueFireRate",
				amount = 15,
				tier = 1,
				links = "parent",
				pos = {1,0},
				parent = "mgb6"
			},
			{
				ref = "excessFreezing",
				name = "excess_freezing",
				trait = "orbOfColdSpeedPercent",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = {0,1},
				parent = "mgb9"
			},
			{
				ref = "gbs1",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = {"cloglessGlueNozzle", "excessFreezing"},
				pos = {1,-1},
				parent = "cloglessGlueNozzle"
			}
		},
		{
			{
				ref = "gbs2",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "cloglessGlueNozzle"
			},
			{
				ref = "gbs3",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbs2"
			},
			{
				ref = "gbs4",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbs3"
			},
			{
				ref = "gbs5",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbs4"
			},
			{
				ref = "gbs6",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbs5"
			},
			{
				ref = "gbs7",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0.5,1},
				parent = "gbs6"
			},
			{
				ref = "gbs8",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {0.5,1},
				parent = "gbs7"
			},
		},
		{
			{
				ref = "gbs9",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "excessFreezing"
			},
			{
				ref = "gbs10",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbs9"
			},
			{
				ref = "gbs11",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbs10"
			},
			{
				ref = "gbs12",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbs11"
			},
			{
				ref = "gbs13",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbs12"
			},
			{
				ref = "gbs14",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0.5},
				parent = "gbs13"
			},
			{
				ref = "gbs15",
				name = "gballoon_sabotage",
				trait = "gBalloonSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0.5},
				parent = "gbs14"
			},
		},
		{
			{
				ref = "notSoFast",
				name = "not_so_fast",
				trait = "gBalloonFastSpeed",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = {1,1},
				parent = "gbs8"
			},
			{
				ref = "notSoHealthy",
				name = "not_so_healthy",
				trait = "gBalloonRegenRate",
				amount = -15,
				tier = 1,
				links = "parent",
				pos = {1,1},
				parent = "gbs15"
			}
		},
		{
			{
				ref = "agbs1",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {1,-1},
				parent = "notSoFast"
			},
			{
				ref = "agbs2",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {1,-1},
				parent = "agbs1"
			},
			{
				ref = "agbs3",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {1,-1},
				parent = "agbs2"
			},
			{
				ref = "agbs4",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {-1,1},
				parent = "notSoHealthy"
			},
			{
				ref = "agbs5",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {-1,1},
				parent = "agbs4"
			},
			{
				ref = "agbs6",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {-1,1},
				parent = "agbs5"
			},
			{
				ref = "causalityExplosions",
				name = "causality_explosions",
				trait = "gBalloonErrorExplosionUnimmune",
				amount = 1,
				tier = 1,
				links = {"agbs3", "agbs6"},
				pos = {1,-1},
				parent = "agbs3"
			},
		},
		{
			{
				ref = "agbs7",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "causalityExplosions"
			},
			{
				ref = "agbs8",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "agbs7"
			},
			{
				ref = "bigArmorMalfunction",
				name = "big_armor_malfunction",
				trait = "gBlimpAndBossArmoredArmor",
				amount = -2,
				tier = 1,
				links = "parent",
				pos = {1,1},
				parent = "agbs8"
			},
			{
				ref = "agbs9",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {-1,-1},
				parent = "causalityExplosions"
			},
			{
				ref = "agbs10",
				name = "advanced_gballoon_sabotage",
				trait = "gBlimpAndBossOuterHealth",
				amount = -1,
				links = "parent",
				pos = {-1,-1},
				parent = "agbs9"
			},
			{
				ref = "fimtrtm",
				name = "fimtrtm",
				trait = "gBalloonFireGeneric",
				amount = 1,
				tier = 1,
				links = "parent",
				pos = {-1,-1},
				parent = "agbs10"
			},
		},
		{
			{
				ref = "fab1",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = {0,math.sqrt(2)},
				parent = "causalityExplosions"
			},
			{
				ref = "fab2",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = {0,math.sqrt(2)},
				parent = "fab1"
			},
			{
				ref = "id1",
				name = "instant_deflator",
				trait = "gBalloonChildrenSuppressChance",
				amount = 5,
				tier = 1,
				links = "parent",
				pos = {0,math.sqrt(2)},
				parent = "fab2"
			}
		},
		{
			{
				ref = "fab3",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(math.sqrt(2),0),
				parent = "causalityExplosions"
			},
			{
				ref = "fab4",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(math.sqrt(2),0),
				parent = "fab3"
			},
			{
				ref = "id2",
				name = "instant_deflator",
				trait = "gBalloonChildrenSuppressChance",
				amount = 5,
				tier = 1,
				links = "parent",
				pos = VectorTable(math.sqrt(2),0),
				parent = "fab4"
			}
		},
		{
			{
				ref = "fab5",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = {0,-math.sqrt(2)},
				parent = "causalityExplosions"
			},
			{
				ref = "fab6",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = {0,-math.sqrt(2)},
				parent = "fab5"
			},
			{
				ref = "id3",
				name = "instant_deflator",
				trait = "gBalloonChildrenSuppressChance",
				amount = 5,
				tier = 1,
				links = "parent",
				pos = {0,-math.sqrt(2)},
				parent = "fab6"
			}
		},
		{
			{
				ref = "fab7",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(-math.sqrt(2),0),
				parent = "causalityExplosions"
			},
			{
				ref = "fab8",
				name = "fair_and_balanced",
				trait = "gBalloonCritChance",
				amount = 1,
				links = "parent",
				pos = VectorTable(-math.sqrt(2),0),
				parent = "fab7"
			},
			{
				ref = "id4",
				name = "instant_deflator",
				trait = "gBalloonChildrenSuppressChance",
				amount = 5,
				tier = 1,
				links = "parent",
				pos = VectorTable(-math.sqrt(2),0),
				parent = "fab8"
			}
		},
		{
			{
				ref = "gbls1",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "notSoFast"
			},
			{
				ref = "gbls2",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "gbls1"
			},
			{
				ref = "gbls3",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0.5},
				parent = "gbls2"
			},
			{
				ref = "gbls4",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0.5},
				parent = "gbls3"
			},
			{
				ref = "gbls5",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbls4"
			},
			{
				ref = "gbls6",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,0},
				parent = "gbls5"
			},
			{
				ref = "gbls7",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,-0.5},
				parent = "gbls6"
			},
			{
				ref = "gbls8",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,-0.5},
				parent = "gbls7"
			},
		},
		{
			{
				ref = "gbls9",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "notSoHealthy"
			},
			{
				ref = "gbls10",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {1,1},
				parent = "gbls9"
			},
			{
				ref = "gbls11",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {0.5,1},
				parent = "gbls10"
			},
			{
				ref = "gbls12",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {0.5,1},
				parent = "gbls11"
			},
			{
				ref = "gbls13",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbls12"
			},
			{
				ref = "gbls14",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {0,1},
				parent = "gbls13"
			},
			{
				ref = "gbls15",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {-0.5,1},
				parent = "gbls14"
			},
			{
				ref = "gbls16",
				name = "gblimp_sabotage",
				trait = "gBlimpAndBossSpeed",
				amount = -1,
				links = "parent",
				pos = {-0.5,1},
				parent = "gbls15"
			},
		},
		{
			ref = "hdtgpqa",
			name = "hdtgpqa",
			trait = "gBalloonOuterArmor",
			amount = -1,
			tier = 2,
			links = {"gbls8", "gbls16"},
			pos = {1,-1},
			parent = "gbls8"
		},
	}
}