AddCSLuaFile()

ENT.Base = "gballoon_tower_base"
ENT.Type = "anim"
ENT.PrintName = "Hoverball Factory"
ENT.Category = "RotgB: Towers"
ENT.Author = "Piengineer"
ENT.Contact = "http://steamcommunity.com/id/Piengineer12/"
ENT.Purpose = "Triumph those gBalloons!"
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.RenderGroup = RENDERGROUP_BOTH
ENT.Model = Model("models/maxofs2d/hover_plate.mdl")
ENT.FireRate = 10
ENT.Cost = 750
ENT.AbilityCooldown = 60
ENT.LOSOffset = Vector(0,0,5)
ENT.AttackDamage = 0
ENT.DetectionRadius = 0
ENT.SeeCamo = true
ENT.InfiniteRange = true
ENT.rotgb_HoverballWorth = 50
ENT.rotgb_HoverballLife = 20
ENT.rotgb_HoverballDelay = 90
ENT.rotgb_BankFactor = 0
ENT.rotgb_BankMax = 100
ENT.rotgb_HoverballPostCash = 0
ENT.rotgb_Buff = 0
ENT.rotgb_HoverballModel = "models/maxofs2d/hover_classic.mdl"
ENT.UpgradeReference = {
	{
		Names = {"Fast Generation", "Advanced Hoverballs", "Faster Generation", "Elite Hoverballs", "Ultimate Hoverballs", "The Big Bill Balls"},
		Descs = {
			"Slightly increases hoverball generation speed.\n(Hoverballs can be sold / removed for $50 each. You can simply touch them to remove them. This tower only generates while gBalloons are present, regardless of upgrades.)",
			"Slightly increases hoverball sell price.",
			"Considerably increases hoverball generation speed.",
			"Slightly decreases hoverball generation speed, but colossally increases hoverball sell price.",
			"Considerably decreases hoverball generation speed to further increase hoverball price.",
			"Yes."
		},
		Prices = {450,700,2000,7500,45000,300000},
		Funcs = {
			function(self)
				self.rotgb_HoverballDelay = self.rotgb_HoverballDelay / 1.5
			end,
			function(self)
				self.rotgb_HoverballWorth = self.rotgb_HoverballWorth * 1.5
				self.rotgb_HoverballModel = "models/dav0r/hoverball.mdl"
			end,
			function(self)
				self.rotgb_HoverballDelay = self.rotgb_HoverballDelay / 2
			end,
			function(self)
				self.rotgb_HoverballDelay = self.rotgb_HoverballDelay * 1.5
				self.rotgb_HoverballWorth = self.rotgb_HoverballWorth * 5
				self.rotgb_HoverballModel = "models/maxofs2d/hover_rings.mdl"
			end,
			function(self)
				self.rotgb_HoverballDelay = self.rotgb_HoverballDelay * 2
				self.rotgb_HoverballWorth = self.rotgb_HoverballWorth * 10
				self.rotgb_HoverballModel = "models/maxofs2d/hover_basic.mdl"
			end,
			function(self)
				self.rotgb_HoverballDelay = self.rotgb_HoverballDelay * 3
				self.rotgb_HoverballWorth = self.rotgb_HoverballWorth * 20
				self.rotgb_HoverballSkin = true
			end
		}
	},
	{
		Names = {"Long Lasting Hoverballs", "Auto-Sell", "Compound Interest", "Garry's Bank", "Grand Metropolis", "INFINITE GROWTH!"},
		Descs = {
			"Hoverballs last for 200% longer.",
			"Hoverballs are now automatically removed. All health generated by this tower is doubled.",
			"For each player, this tower generates additional cash equal to 0.1% of their current cash per second, up to $100 per second. Only works while gBalloons are present.",
			"This tower now generates 0.2% interest, up to $500 per second.",
			"This tower now generates interest from current cash AND placed towers, up to $10,000 per second.",
			"This tower no longer has a maximum interest rate! Once every 60 seconds, shooting at this tower doubles everyone's current cash!"
		},
		Prices = {450,1300,4000,20000,400000,100000000},
		Funcs = {
			function(self)
				self.rotgb_HoverballLife = self.rotgb_HoverballLife * 3
			end,
			function(self)
				self.rotgb_AutoHoverball = true
			end,
			function(self)
				self.rotgb_BankFactor = 0.001
			end,
			function(self)
				self.rotgb_BankFactor = 0.002
				self.rotgb_BankMax = 500
			end,
			function(self)
				self.rotgb_BankMax = 10000
				self.rotgb_BankBonus = true
			end,
			function(self)
				self.rotgb_BankMax = math.huge
				self.HasAbility = true
			end
		}
	},
	{
		Names = {"A Little Extra", "Just Pocket It", "Fuzzy Income", "King of Hearts", "Microbot Research", "Nanomachines"},
		Descs = {
			"At the start of each round, gain 10 seconds worth of hoverball cash.",
			"This tower no longer generates hoverballs. Instead, at the start of each round, gain 45 seconds worth of hoverball cash that would have been generated.",
			"Each round, hoverball cash production is altered to a random number between 0% and 400%.",
			"At the end of each round, all gBalloon Targets gain 20 health.",
			"At the end of each round, the hoverballs' selling values are multiplied by 1.15!",
			"At the end of each round, all gBalloon Targets' health are multiplied by 1.15!"
		},
		Prices = {450,1000,2000,5000,20000,75000},
		Funcs = {
			function(self)
				self.rotgb_HoverballPostCash = 10
			end,
			function(self)
				self.rotgb_NoHoverball = true
				self.rotgb_HoverballPostCash = self.rotgb_HoverballPostCash * 4.5
			end,
			function(self)
				self.rotgb_Trading = true
			end,
			function(self)
				self.rotgb_Buff = 1
			end,
			function(self)
				self.rotgb_Buff = 2
			end,
			function(self)
				self.rotgb_Buff = 3
			end
		}
	}
}
ENT.UpgradeLimits = {8,2,0}

function ENT:FireFunction(gBalloons)
	local cmul = GetConVar("rotgb_cash_mul"):GetFloat()
	self.rotgb_HoverballCharge = (self.rotgb_HoverballCharge or 0) + 1
	if self.rotgb_HoverballCharge >= self.rotgb_HoverballDelay and self.rotgb_HoverballWorth > 0 and not self.rotgb_NoHoverball then
		self.rotgb_HoverballCharge = 0
		if self.rotgb_AutoHoverball then
			ROTGB_AddCash(self.rotgb_HoverballWorth*cmul, self:GetTowerOwner())
			local effdata = EffectData()
			effdata:SetEntity(self)
			util.Effect("entity_remove",effdata,true,true)
		else
			local hoverball = ents.Create("gmod_hoverball")
			hoverball:SetPos(self:LocalToWorld(self.LOSOffset*2))
			hoverball:SetModel(self.rotgb_HoverballModel)
			hoverball:SetSkin(self.rotgb_HoverballSkin and 3 or 0)
			hoverball:Spawn()
			hoverball:SetModelScale(self.rotgb_HoverballSkin and 3 or 1)
			hoverball:Activate()
			hoverball:AddEffects(EF_ITEM_BLINK)
			local physobj = hoverball:GetPhysicsObject()
			if IsValid(physobj) then
				local randnum = math.random()*math.pi*2
				local dirvec = Vector(math.sin(randnum), math.cos(randnum), 0)
				physobj:Wake()
				physobj:SetVelocity(dirvec*350/self.rotgb_HoverballDelay)
			end
			hoverball.rotgb_Value = self.rotgb_HoverballWorth
			hoverball:SetTrigger(true)
			hoverball:UseTriggerBounds(true,64)
			function hoverball:StartTouch(ent)
				if (IsValid(ent) and ent:IsPlayer()) then
					hoverball:SetTrigger(false)
					hoverball:SetNotSolid(true)
					hoverball:SetMoveType(MOVETYPE_NONE)
					hoverball:SetNoDraw(true)
					local effdata = EffectData()
					effdata:SetEntity(hoverball)
					util.Effect("entity_remove",effdata,true,true)
					return SafeRemoveEntityDelayed(hoverball,1)
				end
			end
			hoverball:CallOnRemove("RotgB.Hoverball",function()
				ROTGB_AddCash(hoverball.rotgb_Value*cmul, IsValid(self) and self:GetTowerOwner())
			end)
			timer.Simple(self.rotgb_HoverballLife,function()
				if IsValid(hoverball) then
					hoverball.rotgb_Value = 0
					hoverball:Remove()
				end
			end)
		end
	end
	self.rotgb_BankCharge = (self.rotgb_BankCharge or 0) + 1
	if self.rotgb_BankCharge >= 10 and self.rotgb_BankFactor > 0 then
		self.rotgb_BankCharge = 0
		local cashtoadd = {}
		if self.rotgb_BankBonus then
			for k,v in pairs(ents.GetAll()) do
				if (v.Base == "gballoon_tower_base" and IsValid(v:GetTowerOwner())) then
					local towerowner = v:GetTowerOwner()
					cashtoadd[towerowner] = (cashtoadd[towerowner] or 0) + (v.SellAmount or 0)
				end
			end
			for k,v in pairs(player.GetAll()) do
				ROTGB_AddCash(math.min(self.rotgb_BankMax, (ROTGB_GetCash(v) + (cashtoadd[v] or 0) ) * self.rotgb_BankFactor * cmul), v)
			end
		else
			for k,v in pairs(player.GetAll()) do
				ROTGB_AddCash(math.min(self.rotgb_BankMax,ROTGB_GetCash(v)*self.rotgb_BankFactor*cmul),v)
			end
		end
	end
	if not IsValid(self.rotgb_Spawner) then
		self:SetName("ROTGB_TOWER_16_"..self:GetCreationID())
		self.rotgb_Spawner = ents.FindByClass("gballoon_spawner")[1]
		if self.rotgb_Spawner then
			self.rotgb_Spawner:Fire("AddOutput","OnWaveStart "..self:GetName()..":GainEndCash::0:-1")
		end
	end
end

function ENT:ROTGB_AcceptInput(input,activator,caller,data)
	if input:lower()=="gainendcash" then
		local buff = self.rotgb_Buff
		ROTGB_AddCash(self.rotgb_HoverballWorth*self.FireRate/self.rotgb_HoverballDelay*self.rotgb_HoverballPostCash
		*(self.rotgb_Trading and math.random()*4 or 1)*GetConVar("rotgb_cash_mul"):GetFloat(), self:GetTowerOwner())
		if buff > 0 then
			if buff > 1 then
				self.rotgb_HoverballWorth = self.rotgb_HoverballWorth * 1.15
			end
			for k,v in pairs(ents.FindByClass("gballoon_target")) do
				v:SetHealth(v:Health()+(self.rotgb_AutoHoverball and 40 or 20))
				if buff > 2 then
					v:SetHealth(v:Health()*(self.rotgb_AutoHoverball and 1.3 or 1.15))
				end
			end
		end
	end
end

function ENT:TriggerAbility()
	for k,v in pairs(player.GetAll()) do
		ROTGB_AddCash(ROTGB_GetCash(v)*GetConVar("rotgb_cash_mul"):GetFloat(),v)
	end
end

list.Set("NPC","gballoon_tower_16",{
	Name = ENT.PrintName,
	Class = "gballoon_tower_16",
	Category = ENT.Category
})